version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
      - "1338:1338"
    depends_on:
      - web
    volumes:
      - type: bind
        source: /srv/digital-archive-server/  # example directory
        target: /home/digital-archive-server/static
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  rabbitmq:
    image: rabbitmq:3.11-alpine
    env_file:
      - ./.env
    ports:
      - '5672:5672'
      - '15672:15672'
  celery:
    build: .
    command: celery -A ContentManager worker -l info
    volumes:
      - type: bind
        source: /srv/digital-archive-server/
        target: /home/digital-archive-server/static
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
  web:
    build: .
    command: gunicorn DigitalArchiveServer.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DATABASE_URL
    volumes:
      - type: bind
        source: /srv/digital-archive-server/
        target: /home/digital-archive-server/static
    expose:
      - 8000
    depends_on:
      - db
      - rabbitmq
      - celery
    env_file:
      - ./.env


volumes:
  postgres_data: