# Generated by Django 4.1.3 on 2022-12-16 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManager', '0005_archiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiver',
            name='related_types',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='content',
            name='from_archiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentManager.archiver'),
        ),
        migrations.AddField(
            model_name='creator',
            name='from_archiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentManager.archiver'),
        ),
        migrations.AddField(
            model_name='tag',
            name='from_archiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentManager.archiver'),
        ),
        migrations.AlterField(
            model_name='archiver',
            name='codename',
            field=models.CharField(max_length=32),
        ),
    ]
