# Generated by Django 4.1.3 on 2022-12-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManager', '0006_archiver_related_types_content_from_archiver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiver',
            options={'permissions': [('can_archive', 'Can order archival')]},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'permissions': [('adult_content', 'Can View 18+ content')]},
        ),
    ]
