# Generated by Django 4.1.3 on 2022-12-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManager', '0007_alter_archiver_options_alter_content_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creator',
            name='adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='adult',
            field=models.BooleanField(default=False),
        ),
    ]
