# Generated by Django 4.1.3 on 2022-12-19 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManager', '0008_collection_adult_creator_adult_tag_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='from_archiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ContentManager.archiver'),
        ),
    ]
