# Generated by Django 4.1.3 on 2022-12-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManager', '0009_alter_content_from_archiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiver',
            name='adult',
            field=models.BooleanField(default=False),
        ),
    ]
