# Generated by Django 4.1.3 on 2022-12-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManager', '0011_alter_content_copyright_alter_content_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='creator',
            name='creator_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='creator',
            name='source_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='creator',
            name='source_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='source_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='source_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
