# Generated by Django 4.1.3 on 2023-01-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManager', '0012_alter_creator_about_alter_creator_creator_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='search',
            field=models.JSONField(null=True),
        ),
    ]
