# Generated by Django 4.1.3 on 2023-02-06 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManager', '0013_collection_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='creator',
            name='adult',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='creator',
            name='creator_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='creator',
            name='from_archiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentManager.archiver'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='creator',
            name='source_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='adult',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='from_archiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentManager.archiver'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='source_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
