# Generated by Django 4.1.3 on 2023-02-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManager', '0014_alter_creator_about_alter_creator_adult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='adult',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='collection_content', to='ContentManager.content'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='restricted_access',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='search',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
