# Generated by Django 4.1.3 on 2022-12-04 22:23

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag_id', models.CharField(max_length=255, null=True)),
                ('source_url', models.CharField(max_length=255, null=True)),
                ('source_id', models.CharField(max_length=255, null=True)),
                ('preview', models.CharField(default="<p class='preview'>This tag has no generated preview</p>", max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creator_id', models.CharField(max_length=255, null=True)),
                ('about', models.TextField(null=True)),
                ('source_url', models.CharField(max_length=255, null=True)),
                ('source_id', models.CharField(max_length=255, null=True)),
                ('preview', models.CharField(default="<p class='preview'>This creator has no generated preview</p>", max_length=512)),
                ('related_creators', models.ManyToManyField(null=True, related_name='related_creators', to='ContentViewer.creator')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('source_url', models.CharField(max_length=255)),
                ('source_id', models.CharField(max_length=255)),
                ('content_path', models.CharField(max_length=255)),
                ('time_retrieved', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(null=True)),
                ('time_created', models.DateTimeField(null=True)),
                ('language', models.CharField(max_length=255, null=True)),
                ('copyright', models.CharField(max_length=255, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('content_size', models.PositiveIntegerField()),
                ('preview', models.CharField(default="<p class='preview'>This content has no generated preview</p>", max_length=512)),
                ('creators', models.ManyToManyField(null=True, related_name='content_creators', to='ContentViewer.creator')),
                ('liked_by', models.ManyToManyField(related_name='content_liked_by', to=settings.AUTH_USER_MODEL)),
                ('related_content', models.ManyToManyField(null=True, related_name='related_content', to='ContentViewer.content')),
                ('seen_by', models.ManyToManyField(related_name='content_seen_by', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(null=True, related_name='content_tags', to='ContentViewer.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.CharField(default="<p class='preview'>This collection has no generated preview</p>", max_length=512)),
                ('related_collections', models.ManyToManyField(null=True, related_name='related_collections', to='ContentViewer.collection')),
            ],
        ),
    ]
