# Generated by Django 4.1.3 on 2022-12-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentViewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='related_collections',
            field=models.ManyToManyField(to='ContentViewer.collection'),
        ),
        migrations.AlterField(
            model_name='content',
            name='creators',
            field=models.ManyToManyField(related_name='content_creators', to='ContentViewer.creator'),
        ),
        migrations.AlterField(
            model_name='content',
            name='related_content',
            field=models.ManyToManyField(to='ContentViewer.content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(related_name='content_tags', to='ContentViewer.tag'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='related_creators',
            field=models.ManyToManyField(to='ContentViewer.creator'),
        ),
    ]
