# Generated by Django 4.1.3 on 2022-12-05 01:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ContentViewer', '0003_collection_can_access_collection_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='can_access',
            field=models.ManyToManyField(blank=True, related_name='collection_can_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='related_collections',
            field=models.ManyToManyField(blank=True, to='ContentViewer.collection'),
        ),
        migrations.AlterField(
            model_name='content',
            name='copyright',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='creators',
            field=models.ManyToManyField(blank=True, related_name='content_creators', to='ContentViewer.creator'),
        ),
        migrations.AlterField(
            model_name='content',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='content_liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='related_content',
            field=models.ManyToManyField(blank=True, to='ContentViewer.content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='content_seen_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='content_tags', to='ContentViewer.tag'),
        ),
        migrations.AlterField(
            model_name='content',
            name='time_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='creator_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='related_creators',
            field=models.ManyToManyField(blank=True, to='ContentViewer.creator'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='source_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='source_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
